version: '3'
services:
  repl:
    build: .
    command: ruby entrypoint.rb
    volumes:
      - '.:/playground'

  selenium:
    image: selenium/standalone-chrome-debug:3.8.1-aluminum
    ports:
      - "4444:4444"
      - "5900:5900"

  http:
    image: danjellz/http-server
    volumes:
      - ./public:/public
    ports:
      - 8080:8080
